---
# Source: backstage/templates/backstage-auth-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-auth
data:
  AUTH_GOOGLE_CLIENT_ID: a
  AUTH_GITHUB_CLIENT_ID: c
  AUTH_GITLAB_CLIENT_ID: b
  # This should not be prefixed with AUTH_. This could be a typo in the Backstage app config.
  # Regardless, it is not decided by me.
  GITLAB_BASE_URL: b
  AUTH_OKTA_CLIENT_ID: b
  AUTH_OKTA_AUDIENCE: b
  AUTH_OAUTH2_CLIENT_ID: b
  AUTH_OAUTH2_AUTH_URL: b
  AUTH_OAUTH2_TOKEN_URL: b
  AUTH_AUTH0_CLIENT_ID: b
  AUTH_AUTH0_DOMAIN: b
  AUTH_MICROSOFT_CLIENT_ID: f
  AUTH_MICROSOFT_TENANT_ID: f
