---
# Source: backstage/templates/backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-backend
type: Opaque
stringData:
  AUTH_GOOGLE_CLIENT_SECRET: a
  AUTH_GITHUB_CLIENT_SECRET: c
  AUTH_GITLAB_CLIENT_SECRET: b
  AUTH_OKTA_CLIENT_SECRET: b
  AUTH_OAUTH2_CLIENT_SECRET: b
  AUTH_AUTH0_CLIENT_SECRET: b
  AUTH_MICROSOFT_CLIENT_SECRET: f
  SENTRY_TOKEN: e
  ROLLBAR_ACCOUNT_TOKEN: f
  CIRCLECI_AUTH_TOKEN: r
  GITHUB_TOKEN: g
  GITLAB_TOKEN: g
  AZURE_TOKEN: h
  NEW_RELIC_REST_API_KEY: r
  TRAVISCI_AUTH_TOKEN: fake-travis-ci-auth-token
  PAGERDUTY_TOKEN: h
