---
# Source: backstage/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgresql
  namespace: "test"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.2
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "NEtaVU5nT2F3aQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
